Field Manager module and rename
fmalatino/PyFMS pull request #3
Opened 2024-10-29 18:31 UTC by fmalatino

**Description**
This PR adds a field manager module, which is a port of the FMS `field_manager` module. This new module relies on Python built-in dictionary methods, `dacite` for generating dataclasses from yaml files, and `PyYAML` for parsing yaml files which contain the data for building a `FieldTable` instance. 

Currently this module only supports field tables that are defined in yaml files per the style set forth by FMS in the [`gfdl_msd_schemas`](https://github.com/NOAA-GFDL/gfdl_msd_schemas) repository.

Unit tests for the new methods are contained within `tests/test_field_manager.py`

**How Has This Been Tested?**
All new methods were tested using the unit tests in the `tests` directory.

**Checklist:**
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included

2024-12-24 17:09 UTC, mlee03 requested changes

2024-12-24 17:09 UTC, mlee03 commented on pyfms/field_manager/pyFMS_field_manager.py
> +    modlist: List[Dict]
does the user have to send in the modlist?  I thought to use pyfield_manager, the users just need to specify the field_table.yaml and field_table created a dict that can be queried.

2024-12-24 17:14 UTC, mlee03 commented
Could a bit of comments be added to make reviewing easier?

2024-12-24 17:22 UTC, fmalatino commented on pyFMS/pyfms/__init__.py
> +from .field_manager.pyFMS_field_manager import FieldTable, FieldError
Not necessarily, this will not be visible when importing the methods though either.

2024-12-24 17:22 UTC, fmalatino commented on pyFMS/pyfms/pyFMS_error.py
> +def pyfms_error(mod_name: str, method_name: str, err_msg: str):
I will amend this to use that method once I have the Python calling method fully vetted. Can this change be non-blocking?

2024-12-24 17:23 UTC, fmalatino commented on pyfms/mpp/pyFMS_mpp.py
> +import ctypes as ct
Yes, but were not part of this PR and so they were not included.

2024-12-24 17:24 UTC, fmalatino commented on pyfms/field_manager/pyFMS_field_manager.py
> +    modlist: List[Dict]
No they do not, they only need to provide the field_table.yaml as you described.

2024-12-24 17:27 UTC, fmalatino commented on pyFMS/pyfms/__init__.py
> +from .field_manager.pyFMS_field_manager import FieldTable, FieldError
I will elevate the `pyFMS_field_manager` module

2025-01-07 13:03 UTC, mlee03 commented
I  must be missing something.  All your unit tests are from FieldTable.from_dict(config).  Where's the read in equivalent, for example, I expected something like FieldTable.from_file('"field_table.yaml").  Or do you expect the users to explicitly safe_load the file themselves?

2025-01-07 13:31 UTC, fmalatino commented
> I  must be missing something.  All your unit tests are from FieldTable.from_dict(config).  Where's the read in equivalent, for example, I expected something like FieldTable.from_file('"field_table.yaml").  Or do you expect the users to explicitly safe_load the file themselves? 

My intention was for the user to use safe_load. I will add an additional from_file method that will handle the yaml loading, and will also be called by from_dict.

2025-01-07 13:43 UTC, mlee03 commented on pyfms/pyFMS_field_manager.py
> +                self.model_type = self.modlist[0]["model_type"]
What happens when there are more than one element in modlist?  For example, one for atmos_mod and another for land_mod?

2025-01-07 13:43 UTC, mlee03 commented on pyfms/pyFMS_field_manager.py
> +                self.varlist = self.modlist[0]["varlist"]
Likewise, varlist then would be model_type dependent

2025-01-08 16:48 UTC, fmalatino commented
@mlee03 and @bensonr , I have added an additional test within the unit test included with this PR for accessing a second module from the `modlist` and checking all methods on that module as well.

Also, per the discussion at yesterday's (7 Jan 2025) sprint, I am not sure if it was decided that this PR gets brought in, and then pared down to only the methods needed, or should reviews be held off until later?

2025-01-08 17:44 UTC, mlee03 approved these changes

2025-01-08 17:45 UTC, mlee03 commented
One vote for merging it in now :)

2025-01-21 20:05 UTC, merged